"use client";

import { Reply, Sparkles } from "lucide-react";
import type { GenerationResult } from "@/lib/types";
import { TestCard } from "./TestCard";

type Props = {
  result: GenerationResult;
};

export function ResultsSection({ result }: Props) {
  return (
    <section className="animate-slide-up space-y-12 pt-12">
      {/* Reusable tests */}
      <div>
        <SectionHeader
          icon={<Reply className="h-3.5 w-3.5" />}
          eyebrow="Retrieved from corpus"
          title="Top 5 Reusable Test Cases"
          description="Existing tests from the Methods2Test corpus most semantically similar to your focal method, ranked by cosine similarity."
        />
        <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3">
          {result.reusable.map((test, index) => (
            <TestCard key={test.id} test={test} rank={index + 1} />
          ))}
        </div>
      </div>

      {/* Amplified test */}
      <div>
        <SectionHeader
          icon={<Sparkles className="h-3.5 w-3.5" />}
          eyebrow="Generated by AI"
          title="AI-Amplified Test Case"
          description="A new JUnit test generated by the model to cover behavior that the retrieved tests above don't exercise."
          accent
        />
        <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:max-w-2xl">
          {result.amplified ? (
            <TestCard test={result.amplified} />
          ) : (
            <AmplifiedLoadingCard />
          )}
        </div>
      </div>
    </section>
  );
}

function AmplifiedLoadingCard() {
  return (
    <div className="relative flex flex-col gap-3 rounded-2xl border border-white/5 bg-ink-800/60 p-5 backdrop-blur-xl">
      {/* Badge skeleton */}
      <div className="flex items-center gap-2">
        <span className="inline-flex items-center gap-1 rounded-md border border-accent-400/30 bg-accent-500/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-accent-400">
          <Sparkles className="h-3 w-3 animate-pulse" />
          AI generated
        </span>
      </div>

      {/* Animated shimmer lines */}
      <div className="space-y-2">
        <div className="h-3 w-3/4 animate-pulse rounded-md bg-white/8" />
        <div className="h-3 w-full animate-pulse rounded-md bg-white/5" />
        <div className="h-3 w-5/6 animate-pulse rounded-md bg-white/5" />
        <div className="h-3 w-2/3 animate-pulse rounded-md bg-white/5" />
      </div>

      {/* Status line */}
      <div className="mt-auto flex items-center gap-2 pt-2">
        <span className="inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-accent-400" />
        <span className="text-[11px] text-slate-500">Generating test case…</span>
      </div>
    </div>
  );
}

function SectionHeader({
  icon,
  eyebrow,
  title,
  description,
  accent,
}: {
  icon: React.ReactNode;
  eyebrow: string;
  title: string;
  description: string;
  accent?: boolean;
}) {
  return (
    <div className="max-w-2xl">
      <div
        className={
          accent
            ? "inline-flex items-center gap-1.5 rounded-full border border-accent-400/30 bg-accent-500/10 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wider text-accent-400"
            : "inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wider text-slate-300"
        }
      >
        {icon}
        {eyebrow}
      </div>
      <h2 className="mt-3 text-2xl font-semibold tracking-tight text-white sm:text-3xl">
        {title}
      </h2>
      <p className="mt-2 text-sm leading-relaxed text-slate-400 sm:text-base">
        {description}
      </p>
    </div>
  );
}
